# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'PinkoWinNew' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PinkoWinNew

  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
  pod 'AppsFlyerFramework'

  
  pod 'Capacitor'
  pod 'IonicPortals', '~> 0.6.0'
  pod 'FBSDKCoreKit'
 
end
target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
end
post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
               end
          end
   end
end
