# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'PinkoWin iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PinkoWin iOS
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'

  pod "CapgoInappbrowser", :path => '../node_modules/@capgo/inappbrowser/CapgoInappbrowser.podspec'
  pod 'Capacitor'
  pod 'IonicPortals', '~> 0.6.0'
  pod "CapacitorCamera"

end

target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
end